trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: sample-adh-grafana_backend_plugin-datasource

jobs:
  - job: Tests
    pool:
      name: OpsGuild-Staging1
      demands: Agent.Name -equals IACA5505320
    steps:
      - script: npm ci
        displayName: 'Install dependencies'

      - script: npm test
        displayName: 'Run TS tests'
      
      - script: go get -u github.com/grafana/grafana-plugin-sdk-go
        displayName: 'Install Go SDK for Grafana'
        
      - script: go mod tidy
        displayName: 'Install dependencies'
      
      - script: go test -v ./...
        displayName: 'Run Go Tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '*.xml'
          failTaskOnFailedTests: true
          searchFolder: '$(Build.SourcesDirectory)/coverage'
          testRunTitle: '$(Agent.JobName) on $(Agent.OS)'
        displayName: 'Publish test results'
        condition: always()
      
  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      buildSteps:
        - powershell: |
            $ProgressPreference = 'SilentlyContinue'
            Invoke-WebRequest https://go.dev/dl/go1.18.3.windows-amd64.msi -OutFile go1.18.3.windows-amd64.msi
          workingDirectory: $(Build.SourcesDirectory)
          displayName: 'Download Go'
        
        - script: start /wait msiexec /i go1.18.3.windows-amd64.msi /passive
          displayName: 'Install Go'
          
        - script: echo %PATH%
        
        - script: "C:\Program Files\Go\bin\go" -?
